// <auto-generated />
using System;
using DragonTD.API.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace DragonTD.API.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260529081156_AddEventDefinitions")]
    partial class AddEventDefinitions
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("DragonTD.API.Models.DragonDefinition", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<float>("BaseAttack")
                        .HasColumnType("real");

                    b.Property<float>("BaseDefense")
                        .HasColumnType("real");

                    b.Property<float>("BaseHp")
                        .HasColumnType("real");

                    b.Property<float>("BaseRange")
                        .HasColumnType("real");

                    b.Property<float>("BaseSpeed")
                        .HasColumnType("real");

                    b.Property<int>("Element")
                        .HasColumnType("integer");

                    b.Property<bool>("IsAvailableInGacha")
                        .HasColumnType("boolean");

                    b.Property<string>("Lore")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("ManaCost")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Rarity")
                        .HasColumnType("integer");

                    b.Property<int>("Role")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("DragonDefinitions");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            BaseAttack = 180f,
                            BaseDefense = 80f,
                            BaseHp = 1200f,
                            BaseRange = 4f,
                            BaseSpeed = 3.5f,
                            Element = 0,
                            IsAvailableInGacha = true,
                            Lore = "A young fire dragon born from volcanic eruptions.",
                            ManaCost = 80,
                            Name = "Ignarion",
                            Rarity = 3,
                            Role = 1
                        },
                        new
                        {
                            Id = 2,
                            BaseAttack = 100f,
                            BaseDefense = 120f,
                            BaseHp = 1600f,
                            BaseRange = 3f,
                            BaseSpeed = 2.5f,
                            Element = 1,
                            IsAvailableInGacha = true,
                            Lore = "A guardian of ocean depths who heals allies.",
                            ManaCost = 70,
                            Name = "Aquariel",
                            Rarity = 2,
                            Role = 4
                        },
                        new
                        {
                            Id = 3,
                            BaseAttack = 220f,
                            BaseDefense = 60f,
                            BaseHp = 900f,
                            BaseRange = 5f,
                            BaseSpeed = 5f,
                            Element = 4,
                            IsAvailableInGacha = true,
                            Lore = "Lightning given form — strikes before the thunder.",
                            ManaCost = 90,
                            Name = "Voltaris",
                            Rarity = 3,
                            Role = 3
                        });
                });

            modelBuilder.Entity("DragonTD.API.Models.EventChallengeState", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("BestScore")
                        .HasColumnType("integer");

                    b.Property<string>("EventId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("PlayerId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("PlayerId", "EventId")
                        .IsUnique();

                    b.ToTable("EventChallengeStates");
                });

            modelBuilder.Entity("DragonTD.API.Models.EventDefinition", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("EndUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("EssenceReward")
                        .HasColumnType("integer");

                    b.Property<string>("EventId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("EventType")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("GemReward")
                        .HasColumnType("integer");

                    b.Property<int>("GoldReward")
                        .HasColumnType("integer");

                    b.Property<string>("RewardTiersJson")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("StartUtc")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.ToTable("EventDefinitions");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "Clear patrol objectives and claim a daily account boost.",
                            DisplayName = "Daily Hunt",
                            EndUtc = new DateTime(2030, 12, 31, 23, 59, 59, 0, DateTimeKind.Utc),
                            EssenceReward = 35,
                            EventId = "daily_hunt",
                            EventType = "DailyClaimable",
                            GemReward = 0,
                            GoldReward = 250,
                            RewardTiersJson = "[]",
                            StartUtc = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 2,
                            Description = "Short challenge preview with score tracking.",
                            DisplayName = "Gem Rush",
                            EndUtc = new DateTime(2030, 12, 31, 23, 59, 59, 0, DateTimeKind.Utc),
                            EssenceReward = 0,
                            EventId = "gem_rush",
                            EventType = "ScoredChallenge",
                            GemReward = 0,
                            GoldReward = 0,
                            RewardTiersJson = "[{\"ScoreThreshold\":100,\"GemReward\":10},{\"ScoreThreshold\":500,\"GemReward\":25},{\"ScoreThreshold\":1000,\"GemReward\":50}]",
                            StartUtc = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 3,
                            Description = "Locked until Clan/social backend is active.",
                            DisplayName = "Clan Raid",
                            EndUtc = new DateTime(2030, 12, 31, 23, 59, 59, 0, DateTimeKind.Utc),
                            EssenceReward = 0,
                            EventId = "clan_raid",
                            EventType = "Locked",
                            GemReward = 0,
                            GoldReward = 0,
                            RewardTiersJson = "[]",
                            StartUtc = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        });
                });

            modelBuilder.Entity("DragonTD.API.Models.IapPurchaseReceipt", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("GemsGranted")
                        .HasColumnType("integer");

                    b.Property<string>("Platform")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("PlayerId")
                        .HasColumnType("integer");

                    b.Property<string>("ProductId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Receipt")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("TransactionId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("ValidatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("PlayerId");

                    b.HasIndex("TransactionId")
                        .IsUnique();

                    b.ToTable("IapPurchaseReceipts");
                });

            modelBuilder.Entity("DragonTD.API.Models.Player", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("FirebaseUid")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("GachaPullsSinceLastS")
                        .HasColumnType("integer");

                    b.Property<int>("GachaTotalPulls")
                        .HasColumnType("integer");

                    b.Property<int>("Gems")
                        .HasColumnType("integer");

                    b.Property<int>("Gold")
                        .HasColumnType("integer");

                    b.Property<DateTime>("LastLoginAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("LastSyncedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("PlayerLevel")
                        .HasColumnType("integer");

                    b.Property<long>("PlayerXp")
                        .HasColumnType("bigint");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("FirebaseUid")
                        .IsUnique();

                    b.HasIndex("Username")
                        .IsUnique();

                    b.ToTable("Players");
                });

            modelBuilder.Entity("DragonTD.API.Models.PlayerDragon", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("BondLevel")
                        .HasColumnType("integer");

                    b.Property<float>("BondXp")
                        .HasColumnType("real");

                    b.Property<int>("DragonDefinitionId")
                        .HasColumnType("integer");

                    b.Property<bool>("IsFavorite")
                        .HasColumnType("boolean");

                    b.Property<int>("Level")
                        .HasColumnType("integer");

                    b.Property<DateTime>("ObtainedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("PlayerId")
                        .HasColumnType("integer");

                    b.Property<long>("TotalBattles")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("DragonDefinitionId");

                    b.HasIndex("PlayerId");

                    b.ToTable("PlayerDragons");
                });

            modelBuilder.Entity("DragonTD.API.Models.PlayerEventClaim", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateOnly>("ClaimDateUtc")
                        .HasColumnType("date");

                    b.Property<DateTime>("ClaimedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("EventId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("PlayerId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("PlayerId", "EventId", "ClaimDateUtc")
                        .IsUnique();

                    b.ToTable("PlayerEventClaims");
                });

            modelBuilder.Entity("DragonTD.API.Models.PlayerProgressionState", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("LastBattleRewardJson")
                        .HasColumnType("text");

                    b.Property<int>("PlayerId")
                        .HasColumnType("integer");

                    b.Property<string>("SaveJson")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("PlayerId")
                        .IsUnique();

                    b.ToTable("PlayerProgressionStates");
                });

            modelBuilder.Entity("DragonTD.API.Models.EventChallengeState", b =>
                {
                    b.HasOne("DragonTD.API.Models.Player", "Player")
                        .WithMany()
                        .HasForeignKey("PlayerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Player");
                });

            modelBuilder.Entity("DragonTD.API.Models.IapPurchaseReceipt", b =>
                {
                    b.HasOne("DragonTD.API.Models.Player", "Player")
                        .WithMany()
                        .HasForeignKey("PlayerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Player");
                });

            modelBuilder.Entity("DragonTD.API.Models.PlayerDragon", b =>
                {
                    b.HasOne("DragonTD.API.Models.DragonDefinition", "DragonDefinition")
                        .WithMany()
                        .HasForeignKey("DragonDefinitionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("DragonTD.API.Models.Player", "Player")
                        .WithMany("Dragons")
                        .HasForeignKey("PlayerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("DragonDefinition");

                    b.Navigation("Player");
                });

            modelBuilder.Entity("DragonTD.API.Models.PlayerEventClaim", b =>
                {
                    b.HasOne("DragonTD.API.Models.Player", "Player")
                        .WithMany()
                        .HasForeignKey("PlayerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Player");
                });

            modelBuilder.Entity("DragonTD.API.Models.PlayerProgressionState", b =>
                {
                    b.HasOne("DragonTD.API.Models.Player", "Player")
                        .WithOne()
                        .HasForeignKey("DragonTD.API.Models.PlayerProgressionState", "PlayerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Player");
                });

            modelBuilder.Entity("DragonTD.API.Models.Player", b =>
                {
                    b.Navigation("Dragons");
                });
#pragma warning restore 612, 618
        }
    }
}
